# Pipeline Configuration

# Path to the LAA fastq files
LAA_DATA_PATH: /home/wgallard/MyData/pharmacogenomics_pipeline/preprocessor/96_well_output/LAA

# Path to the genome fasta file to be used for mapping/alignment
# The location of this file should be writable so that indexes can be created
# TODO - put this somewhere accessible by other users
GENOME: /bam-export/Guy/GRCh38_no_alt_analysis_set/sequence/GRCh38_no_alt_analysis_set.fasta

# use an existing last database
# if not specified, the pipeline will create one in the output directory
LASTDB_PATH: /home/wgallard/MyData/smrtpipe_test/GRCh38/GRCh38_no_alt_analysis_set/sequence

# name of the last database
LASTDB_NAME: GRCh38_no_alt_analysis_set

